### ISSUE TITLE
名字会不会太长了？

### ISSUE THREAD

**Issue by lepture** [cn/individual-income-tax-law#1]
有没有简单一点的命名？

**Comment by guo-yu** [comment]
直接用缩写吧

**Comment by lepture** [comment]
> INDIVIDUAL INCOME TAXLAW

http://www.law-lib.com/Law/law_view.asp?id=10170

> Individual Income Tax Law

一般是这样命名的

**Comment by lepture** [comment]
这样子如何？ individual-income-tax-law

**Comment by hotoo** [comment]
没意见。不过还是一样长。

**Comment by guo-yu** [comment]
individual-income-tax-law 感觉比较好

**Comment by hotoo** [comment]
改了。
